language: php
php:
  - '5.6'
  - '7.0'

addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN

before_script: composer install

after_script:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN ./vendor/bin/test-reporter